repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      #- id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    # This mirror is archived, see https://github.com/prettier/prettier/discussions/16227
    # Workaround if newer versions fail: https://github.com/prettier/prettier/issues/15696#issuecomment-2066264028
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        # To avoid "[error] No files matching the given patterns were found" when running locally
        args: [--no-error-on-unmatched-pattern]
        stages:
          - commit
  - repo: https://github.com/openstack/bashate
    rev: 2.1.1
    hooks:
      - id: bashate
        args:
          - -i
          - E006
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shfmt
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.25.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
